Fix preventing starting multiple signups edit
ArmaForces/Boderator pull request #31
Opened 2021-01-06 20:21 UTC by Smieszkokoleszko

It is possible to start signups edit many times for different signups. 
Additional method for checking currently edited or created mission by user. Can be implemented in the most of the methods regarding creating signups.

2021-01-06 21:00 UTC, 3Mydlo3 requested changes
Overall nice, just some enhancements for UX and code quality.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Helpers/SignupHelper.cs
> +        public Mission GetCurrentlyEditedMission(ulong userId, SignupsData signups)
I don't really like the idea of this helper class. In refactor I will try to move these methods where they should be, right now it's real mess.

I think it would be better to create extension method for SignupsData (there is already an `Extensions` folder, create this class there):
```cs
public static class SignupsDataExtensions {
  public static GetCurrentlyEditedMission(this SignupsData signupsData, ulong userId) {
    // logic here
  }
}
```
Then you would call it like this:
```cs
SignupsData.GetCurrentlyEditedMission(Context.User.Id);
```

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +           if (SignupHelper.GetCurrentlyEditedMission(Context.User.Id, SignupsData) == null)
I think you can update all usages in `Signups`, it will get a little bit less messy. Feel free to introduce other helper (extension if possible) methods if you think it will reduce redundant code.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +                var userMissions = SignupsData.Missions.FindAll(x => x.Owner == Context.User.Id && x.Editing == ArmaforcesMissionBotSharedClasses.Mission.EditEnum.NotEditing);
This one seems like a good place to use extension method helper. I guess there are at least dozen similar usages in this file.

Please use `Where` instead of `FindAll` in extension method (so the return value will be `IEnumerable<Mission>` if you decide to create such method), with `.ElementAt()` to retrieve mission.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +                var editMission = userMissions[missionNo];
I think `editMission` is not the best name for it. It's more like `editedMission` or better `missionToBeEdited` as it's not edited yet.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Helpers/SignupHelper.cs
> +            return currentlyEditedMission;
You can just return the result, no need to create `var currentlyEditedMission`.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Helpers/SignupHelper.cs
> +            var currentlyEditedMission = signups.Missions.Find(x =>
Please use `SingleOrDefault` instead of `Find`. It will return `null` when not found, single mission or throw an exception if more than one mission matches predicate.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +                await ReplyAsync("Luzik, co chcesz zmienić?");
Please include something mission-specific (eg. title) in response, so the user can be sure he's editing the correct mission.

2021-01-06 21:00 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +                await ReplyAsync("Hola hola, nie wszystko naraz. Skończ poprzednią edycję.");
You could include currently edited mission title here, so the user won't need to wonder what was/is he editing.

2021-01-06 21:04 UTC, Smieszkokoleszko commented on ArmaforcesMissionBot/Helpers/SignupHelper.cs
> +        public Mission GetCurrentlyEditedMission(ulong userId, SignupsData signups)
Should I do this now or after refactor is done?

2021-01-06 21:04 UTC, Smieszkokoleszko commented on ArmaforcesMissionBot/Modules/Signups.cs
> +           if (SignupHelper.GetCurrentlyEditedMission(Context.User.Id, SignupsData) == null)
Should I do this now or after refactor is done?

2021-01-06 21:06 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +           if (SignupHelper.GetCurrentlyEditedMission(Context.User.Id, SignupsData) == null)
Better now as you introduced this method here, so it's entirely fair to update all shitcode you can.

2021-01-06 21:10 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Helpers/SignupHelper.cs
> +        public Mission GetCurrentlyEditedMission(ulong userId, SignupsData signups)
It's part of your helper method introduction so it should be done here (as the method is not yet in the base branch, you can change how it's implemented).

2021-01-06 22:00 UTC, Smieszkokoleszko commented on ArmaforcesMissionBot/Modules/Signups.cs
> +                await ReplyAsync("Luzik, co chcesz zmienić?");
Maybe add confirmation window like for `AF!koniec`?

2021-01-06 22:03 UTC, 3Mydlo3 commented on ArmaforcesMissionBot/Modules/Signups.cs
> +                await ReplyAsync("Luzik, co chcesz zmienić?");
I don't think it's necessary. If mission will be wrong, user can stop the edition and try again.

2021-01-06 23:37 UTC, Smieszkokoleszko commented
I hope that I resolved all issues. Still not everything was cleaned, but refactor first.

2021-01-21 12:50 UTC, 3Mydlo3 approved these changes

2021-01-21 12:51 UTC, 3Mydlo3 commented
Please resolve the conflicts and let me know when it's done and I'll merge this.

2021-01-29 22:20 UTC, merged